[alias]
check-all = "check --workspace --all-targets --all-features"
test-all = "test --workspace --all-targets --all-features"
lint = "clippy --workspace --all-targets --all-features -- -D warnings"

